apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scaling-winner
  name: scaling-winner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-winner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scaling-winner
    spec:
      containers:
      - image: daveayan/scaling-winner
        name: scaling-winner
        resources: {}
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: scaling-winner
  name: scaling-winner
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: scaling-winner
  type: ClusterIP
status:
  loadBalancer: {}
